{% set name = "cosmoTransitions" %}
{% set version = "2.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cosmoTransitions-{{ version }}.tar.gz
  sha256: aa06b00658275d9e7f35a102e89cc5e640c326bcb70d2389f63dfac5e19826bf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.8
    - scipy >=0.11

test:
  imports:
    - cosmoTransitions
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://clwainwright.net/CosmoTransitions/
  dev_url: https://github.com/clwainwright/CosmoTransitions
  summary: 'A package for analyzing finite or zero-temperature cosmological phase transitions driven by single or multiple scalar fields.'
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - og113
    - clwainwright
