{% set name = "cosmoTransitions" %}
{% set version = "2.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 0f2a52e197e72b742745ec11b0deb93aa198ac3bca887924fb66c2eed946c18c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.8
    - scipy >=0.11

test:
  imports:
    - cosmoTransitions
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://clwainwright.net/CosmoTransitions/
  dev_url: https://github.com/clwainwright/CosmoTransitions
  summary: 'A package for analyzing finite or zero-temperature cosmological phase transitions driven by single or multiple scalar fields.'
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - og113
    - clwainwright
